#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>


int main(void)
{
    int mx = 20;  // 描画する幅。メッシュ数に合わせる。
    int step, step_end = 50;  // 書き出したファイルのステップ分
    char base[256];
    char out_path[256];

    sprintf(base,"./anime/temp_");
    sprintf(out_path, "anime.gp");

    FILE *file;
    file = fopen(out_path, "w");

    fprintf(file,"#\n");
    fprintf(file,"# gnuplot script generated by heat_animation_make.C\n");
    fprintf(file,"#\n");
    fprintf(file,"set xlabel 'j'              # x-axis\n");
    fprintf(file,"set ylabel 'temperature'    # y-axis\n");
    fprintf(file,"set xrange[0:%d]     # j-grid min & max\n", mx+1);
    fprintf(file,"set yrange[0.0:0.5]         # temperature min & max\n");

    for(step=1; step<step_end; step++){
        fprintf(file,"plot './anime/temp_%05d.dat' w lp\n", step);
        if(step==1){
            fprintf(file,"pause 5\n");
        }
        else{
            fprintf(file,"pause 1\n");
        }
    }
    
    fclose(file);
}