#
# gnuplot script generated by heat_animation_make.C
#
set xlabel 'j'              # x-axis
set ylabel 'u'    # y-axis
set xrange[0:1]     # j-grid min & max
set yrange[0.0:0.1]         # temperature min & max

plot 'output.dat' using 1:2 with lines
replot 'output.dat' using 1:3 with lines
replot 'output.dat' using 1:4 with lines